### ISSUE TITLE
Add support for custom DNS resolutions

### ISSUE THREAD

**Issue by dlm31** [f18m/ha-addon-dnsmasq-dhcp#19]
Having issues resolving dns names. I've declard a host named "tapo or tapo.lan", but when I try to resolve either tapo or tapo.lan I get unresolved. Trying this configuration with the original dnsmasq works, but not with this addon.

```
enable: true
port: 53
dns_domain: lan
upstream_servers:
  - 9.9.9.9
hosts:
  - host: tapo
    ip: 192.168.0.65
  - host: tapo.lan
    ip: 192.168.0.65
```

**Comment by f18m** [comment]
hey @dlm31 ,
which dnsmasq-dhcp version are you using? Is it 2.0.1 or a 1.xxx version?

can you confirm that you've trying to resolve the "tapo.lan" FQDN from a machine having its DNS server set to the IP address of the HomeAssistant instance hosting the dnsmasq-dhcp addon ? Typically you can run `resolvectl status` to verify if that's the case.

Moreover the config snippet that you provided... it does not look like a valid dnsmasq-dhcp config syntax:
* the "hosts" key does not exists
* the "dhcp_ip_address_reservations" key (the most similar one to your "hosts") should contain a YAML list with keys "mac", "name", "ip" and "link".

In other words a valid dnsmasq-dhcp config for your case would look like:

```
dns_server:
  enable: true
  port: 53
  dns_domain: lan
  upstream_servers:
    - 9.9.9.9
dhcp_ip_address_reservations:
  - name: tapo
    ip: 192.168.0.65
    mac: <your Tapo MAC address>
```
